package Vista;
import Modelo.cls_parcela;
import Modelo.cls_trabajador;
import java.util.LinkedList;
import javax.swing.JOptionPane;

public class frm_FincaAmigo extends javax.swing.JFrame {

    LinkedList<cls_trabajador>obj_trabajador = new LinkedList<>();
    LinkedList<cls_parcela>obj_parcela = new LinkedList<>();
    
    boolean bln_sw;
    boolean bln_swF;
    int int_pos;
    int int_posF;
    
    public frm_FincaAmigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_codefinca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_nameFinca = new javax.swing.JTextField();
        txt_extention = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_contactF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_DorectionF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_CropsF = new javax.swing.JTextField();
        txt_CodeT = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_guardarParcela = new javax.swing.JButton();
        btn_actualizarParcela = new javax.swing.JButton();
        btn_consultarParcela = new javax.swing.JButton();
        btn_cleanF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbx_title = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbx_sex = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_direction = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        btn_guardarTrabajador = new javax.swing.JButton();
        btn_actualizarTrabajador = new javax.swing.JButton();
        btn_consultarTrabajador = new javax.swing.JButton();
        btn_cleanT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Parcel.");

        jLabel16.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Code:");

        txt_codefinca.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_codefinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codefincaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Name:");

        txt_nameFinca.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_nameFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameFincaActionPerformed(evt);
            }
        });

        txt_extention.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_extention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_extentionActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Extension:");

        jLabel13.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contact:");

        txt_contactF.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_contactF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactFActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Direction:");

        txt_DorectionF.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_DorectionF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DorectionFActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Crops:");

        txt_CropsF.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_CropsF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CropsFActionPerformed(evt);
            }
        });

        txt_CodeT.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_CodeT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CodeTActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Woeker´s Code:");

        btn_guardarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardarParcela.setText("Save");
        btn_guardarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarParcelaActionPerformed(evt);
            }
        });

        btn_actualizarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizarParcela.setText("Update");
        btn_actualizarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarParcelaActionPerformed(evt);
            }
        });

        btn_consultarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cunsultar.png"))); // NOI18N
        btn_consultarParcela.setText("Search");
        btn_consultarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarParcelaActionPerformed(evt);
            }
        });

        btn_cleanF.setText("clean");
        btn_cleanF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_CodeT, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_CropsF, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_DorectionF, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                            .addComponent(txt_extention)
                                            .addComponent(txt_nameFinca)
                                            .addComponent(txt_codefinca)
                                            .addComponent(txt_contactF, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(32, 32, 32))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btn_guardarParcela)
                        .addGap(18, 18, 18)
                        .addComponent(btn_actualizarParcela)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consultarParcela))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_cleanF)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codefinca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_nameFinca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_extention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_contactF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_DorectionF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_CropsF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_CodeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarParcela)
                    .addComponent(btn_actualizarParcela)
                    .addComponent(btn_consultarParcela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cleanF)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Worker.");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Code:");

        txt_code.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name:");

        txt_name.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Title:");

        cbx_title.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        cbx_title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Laborer", "Secretary" }));

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sex:");

        cbx_sex.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        cbx_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Man", "Woman" }));

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Contact:");

        txt_contact.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Direction:");

        txt_direction.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_direction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_directionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Mail");

        txt_mail.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mailActionPerformed(evt);
            }
        });

        btn_guardarTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardarTrabajador.setText("Save");
        btn_guardarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarTrabajadorActionPerformed(evt);
            }
        });

        btn_actualizarTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizarTrabajador.setText("Update");
        btn_actualizarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarTrabajadorActionPerformed(evt);
            }
        });

        btn_consultarTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cunsultar.png"))); // NOI18N
        btn_consultarTrabajador.setText("Search");
        btn_consultarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarTrabajadorActionPerformed(evt);
            }
        });

        btn_cleanT.setText("clean");
        btn_cleanT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_code, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                            .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                            .addComponent(cbx_title, 0, 358, Short.MAX_VALUE)
                                            .addComponent(cbx_sex, 0, 358, Short.MAX_VALUE)
                                            .addComponent(txt_contact)
                                            .addComponent(txt_direction)
                                            .addComponent(txt_mail)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(btn_guardarTrabajador)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_actualizarTrabajador)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_consultarTrabajador)))))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cleanT)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarTrabajador)
                    .addComponent(btn_actualizarTrabajador)
                    .addComponent(btn_consultarTrabajador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cleanT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codeActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void txt_directionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_directionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_directionActionPerformed

    private void txt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mailActionPerformed

    private void txt_codefincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codefincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codefincaActionPerformed

    private void txt_nameFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameFincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameFincaActionPerformed

    private void txt_extentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_extentionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_extentionActionPerformed

    private void txt_contactFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactFActionPerformed

    private void txt_DorectionFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DorectionFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DorectionFActionPerformed

    private void txt_CropsFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CropsFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CropsFActionPerformed

    private void txt_CodeTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CodeTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CodeTActionPerformed

    private void btn_guardarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarTrabajadorActionPerformed
        obj_trabajador.add(new cls_trabajador(
            txt_code.getText(),
            txt_name.getText(),
            (String)cbx_sex.getSelectedItem(),
            (String)cbx_title.getSelectedItem(),
            txt_contact.getText(),
            txt_direction.getText(),
            txt_mail.getText()));
    if(txt_code.getText().equals("")||txt_name.getText().equals("")||txt_contact.getText().equals("")||txt_direction.getText().equals("")||txt_mail.getText().equals("")){
        JOptionPane.showMessageDialog(null, "PLEASE COMPLETE THE INFORMATION","ERROR",JOptionPane.ERROR_MESSAGE);
    }else{
        JOptionPane.showMessageDialog(null, "SAVE SUCCESFULLY","REGISTER",JOptionPane.INFORMATION_MESSAGE);
        fnt_cleanT();
    }

    }//GEN-LAST:event_btn_guardarTrabajadorActionPerformed

    private void fnt_cleanT(){
        txt_code.setText("");
        txt_name.setText("");
        txt_contact.setText("");
        txt_direction.setText("");
        txt_mail.setText("");
    }
    private void fnt_cleanF(){
        txt_codefinca.setText("");
        txt_nameFinca.setText("");
        txt_extention.setText("");
        txt_contactF.setText("");
        txt_DorectionF.setText("");
        txt_CropsF.setText("");
        txt_CodeT.setText("");
    }
    
    private void btn_actualizarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarTrabajadorActionPerformed
      
        bln_sw=false;
        int_pos=0;
        for(int i=0 ; i<obj_trabajador.size() ; i++){
            if(txt_code.getText().equals(obj_trabajador.get(i).getStr_code())){
                bln_sw=true;
                int_pos=i;
                break;
            }
        }
        if(bln_sw==false){
            JOptionPane.showMessageDialog(null, "NO FOUND","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            obj_trabajador.get(int_pos).setStr_nombre(txt_name.getText());
            obj_trabajador.get(int_pos).setStr_title(cbx_title.getSelectedItem().toString());
            obj_trabajador.get(int_pos).setStr_sexo(cbx_sex.getSelectedItem().toString());
            obj_trabajador.get(int_pos).setStr_contaco(txt_contact.getText());
            obj_trabajador.get(int_pos).setStr_direccion(txt_direction.getText());
            obj_trabajador.get(int_pos).setStr_correo(txt_mail.getText());
            JOptionPane.showMessageDialog(null, "UPDATE SUCCESFUL","UPDATE",JOptionPane.INFORMATION_MESSAGE);
        }
        fnt_cleanT();
    }//GEN-LAST:event_btn_actualizarTrabajadorActionPerformed

    private void btn_consultarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarTrabajadorActionPerformed
        bln_sw=false;
        int_pos=0;
        for(int i=0 ; i<obj_trabajador.size() ; i++){
            if(txt_code.getText().equals(obj_trabajador.get(i).getStr_code())){
                bln_sw=true;
                int_pos=i;
                break;
            }
        }
        if(bln_sw==false){
            JOptionPane.showMessageDialog(null, "NO FOUND","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            txt_name.setText(obj_trabajador.get(int_pos).getStr_nombre());
            cbx_title.setSelectedItem(obj_trabajador.get(int_pos).getStr_title());
            cbx_sex.setSelectedItem(obj_trabajador.get(int_pos).getStr_sexo());
            txt_contact.setText(obj_trabajador.get(int_pos).getStr_contaco());
            txt_direction.setText(obj_trabajador.get(int_pos).getStr_direccion());
            txt_mail.setText(obj_trabajador.get(int_pos).getStr_correo());
        }
    }//GEN-LAST:event_btn_consultarTrabajadorActionPerformed

    private void btn_guardarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarParcelaActionPerformed
        obj_parcela.add(new cls_parcela(
            txt_codefinca.getText(),
            txt_nameFinca.getText(),
            txt_extention.getText(),
            txt_contactF.getText(),
            txt_DorectionF.getText(),
            txt_CropsF.getText(),
            txt_CodeT.getText()));
        if(txt_codefinca.getText().equals("")||txt_nameFinca.getText().equals("")||txt_extention.getText().equals("")||txt_contactF.getText().equals("")||
           txt_DorectionF.getText().equals("")||txt_CropsF.getText().equals("")||txt_CodeT.getText().equals("")){
            JOptionPane.showMessageDialog(null, "PLEASE COMPLETE THE INFORMATION","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
        JOptionPane.showMessageDialog(null, "SAVE SUCCESFULLY","REGISTER",JOptionPane.INFORMATION_MESSAGE);
        fnt_cleanF();
        }
    }//GEN-LAST:event_btn_guardarParcelaActionPerformed

    private void btn_actualizarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarParcelaActionPerformed
        bln_swF=false;
        int_posF=0;
        for(int i=0 ; i<obj_parcela.size() ; i++){
            if(txt_codefinca.getText().equals(obj_parcela.get(i).getStr_codigoF())){
                bln_swF=true;
                int_posF=i;
                break;
            }
        }
        if(bln_swF==false){
            JOptionPane.showMessageDialog(null, "NO FOUND","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            obj_parcela.get(int_posF).setStr_nombreF(txt_nameFinca.getText());
            obj_parcela.get(int_posF).setStr_extencion(txt_extention.getText());
            obj_parcela.get(int_posF).setStr_contactoF(txt_contactF.getText());
            obj_parcela.get(int_posF).setStr_direccionP(txt_DorectionF.getText());
            obj_parcela.get(int_posF).setStr_cultivos(txt_CropsF.getText());
            obj_parcela.get(int_posF).setStr_codigoT(txt_CodeT.getText());
            JOptionPane.showMessageDialog(null, "UPDATE SUCCESFUL","UPDATE",JOptionPane.INFORMATION_MESSAGE);
        }
        fnt_cleanF();
    }//GEN-LAST:event_btn_actualizarParcelaActionPerformed

    private void btn_consultarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarParcelaActionPerformed
        bln_swF=false;
        int_posF=0;
        for(int i=0 ; i<obj_parcela.size() ; i++){
            if(txt_codefinca.getText().equals(obj_parcela.get(i).getStr_codigoF())){
                bln_swF=true;
                int_posF=i;
                break;
            }
        }
        if(bln_swF==false){
            JOptionPane.showMessageDialog(null, "NO FOUND","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            txt_nameFinca.setText(obj_parcela.get(int_posF).getStr_nombreF());
            txt_extention.setText(obj_parcela.get(int_posF).getStr_extencion());
            txt_contactF.setText(obj_parcela.get(int_posF).getStr_contactoF());
            txt_DorectionF.setText(obj_parcela.get(int_posF).getStr_direccionP());
            txt_CropsF.setText(obj_parcela.get(int_posF).getStr_cultivos());
            txt_CodeT.setText(obj_parcela.get(int_posF).getStr_codigoT());
        }

    }//GEN-LAST:event_btn_consultarParcelaActionPerformed

    private void btn_cleanTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanTActionPerformed
        fnt_cleanT();
    }//GEN-LAST:event_btn_cleanTActionPerformed

    private void btn_cleanFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanFActionPerformed
        fnt_cleanT();
    }//GEN-LAST:event_btn_cleanFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_FincaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_FincaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_FincaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_FincaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_FincaAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarParcela;
    private javax.swing.JButton btn_actualizarTrabajador;
    private javax.swing.JButton btn_cleanF;
    private javax.swing.JButton btn_cleanT;
    private javax.swing.JButton btn_consultarParcela;
    private javax.swing.JButton btn_consultarTrabajador;
    private javax.swing.JButton btn_guardarParcela;
    private javax.swing.JButton btn_guardarTrabajador;
    private javax.swing.JComboBox<String> cbx_sex;
    private javax.swing.JComboBox<String> cbx_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_CodeT;
    private javax.swing.JTextField txt_CropsF;
    private javax.swing.JTextField txt_DorectionF;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_codefinca;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_contactF;
    private javax.swing.JTextField txt_direction;
    private javax.swing.JTextField txt_extention;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nameFinca;
    // End of variables declaration//GEN-END:variables
}
